version: '3.8'
services:
  frontend:
    build: example-frontend
    ports:
      - 5001:5000
  backend:
    build: example-backend
    ports:
      - 8080:8080
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
  redis:
    image: redis
  postgres:
    image: postgres:alpine3.15
    environment:
      - POSTGRES_PASSWORD=postgres
    container_name: postgres
  proxy:
    image: jwilder/nginx-proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
